# Generated by Django 4.2.5 on 2023-10-03 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=120)),
                ('comment', models.CharField(max_length=240)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
            ],
        ),
    ]
