# Generated by Django 4.2.5 on 2023-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fromDate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='toDate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='times',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(default='', max_length=120),
        ),
    ]
